# Welcome to Skript-Advancement's config.yml!
# Here you can enable/disable different things that Skript-Advancements does.
# Need help? Visit the wiki here: https://github.com/hotpocket184/skript-advancements/wiki

# Should Skript-Advancements reload Bukkit's data when creating/deleting advancements?
# This is essential for having the advancements load without restarting your server.
reload:
  # Keep in mind that if advancements are created too fast then errors will appear. If this happens, it is suggested that you use the reload data effect and set the on-create value to false!
  on-create: false
  on-delete: true

# Set the key of a custom advancement. Keys are the "minecraft" part of "miencraft:adventure/root"
custom-key: "skript"