name: Skript-Advancements
version: '${project.version}'
main: me.hotpocket.skriptadvancements.SkriptAdvancements
api-version: 1.17
depend: [ Skript ]
authors: [ hotpocket184 ]
description: Allows you to manipulate advancements in Skript.
